/**
 * Director Movie Constants
 *
 * Pure data module extracted from legacy director-movies.ts (lines 1-254).
 * Contains core definitions for AI directors, channel branding, and visual styles.
 *
 * Zero external dependencies. Consumed by:
 * - ai-engine (movie trailer generation)
 * - multi-clip (channel content generation)
 * - director-movies-lib (future port, chunks B-D)
 */

export interface DirectorProfile {
  username: string;
  displayName: string;
  genres: string[];       // genres they specialize in
  style: string;          // unique filmmaking style description for prompts
  signatureShot: string;  // their signature visual technique
  colorPalette: string;   // dominant color grading
  cameraWork: string;     // camera movement preferences
  visualOverride: string; // mandatory visual instructions injected into every video prompt
}

export const DIRECTORS: Record<string, DirectorProfile> = {
  steven_spielbot: {
    username: "steven_spielbot",
    displayName: "Steven Spielbot",
    genres: ["family", "scifi", "action", "drama"],
    style: "Warm, emotional storytelling with wonder, family themes, and crowd-pleasing spectacle. Sweeping orchestral scores, childlike awe, heroic lighting, and heartfelt character moments mixed with thrilling adventure. Golden sunlight flares, emotional close-ups with awe-filled expressions, and wonder-filled framing. Every frame radiates hope, wonder, or heartbreak.",
    signatureShot: "A character looking upward in wonder as light streams down from above, backlit silhouette against a dramatic sky",
    colorPalette: "Warm golden tones, amber sunlight, deep blue shadows, lens flare highlights, magic-hour warmth",
    cameraWork: "Slow push-ins on faces, sweeping crane shots, dolly-into-subject reveals, low-angle hero shots, intimate handheld in emotional moments",
    visualOverride: "Golden hour lighting with warm amber tones, dramatic lens flares, emotional close-ups with awe-filled expressions, sweeping orchestral blockbuster feel. Shot on warm film stock with soft highlights. Childlike wonder in every frame.",
  },
  stanley_kubrick_ai: {
    username: "stanley_kubrick_ai",
    displayName: "Stanley Kubr.AI",
    genres: ["horror", "scifi", "drama"],
    style: "Precise, symmetrical compositions, slow methodical pacing, cold intellectual tone, philosophical depth, and haunting beauty. Wide-angle lenses, minimalist sets, classical music, and unsettling perfection in framing. One-point perspective corridors, unsettling stillness, every frame a painting of controlled dread.",
    signatureShot: "A perfectly symmetrical corridor shot with a single figure at the vanishing point, one-point perspective",
    colorPalette: "Cold clinical whites, deep reds, stark monochrome contrasts, desaturated with single color accents",
    cameraWork: "Steadicam tracking through corridors, perfectly centered compositions, slow zoom-ins, static locked-off shots with unbearable tension",
    visualOverride: "Highly desaturated cold clinical look, one-point perspective symmetry, unsettling geometric precision, minimal colour with stark red accents. Wide-angle lenses, minimalist sets. Shot with clinical detachment.",
  },
  george_lucasfilm: {
    username: "george_lucasfilm",
    displayName: "George LucASfilm",
    genres: ["scifi", "action", "family"],
    style: "Epic space opera scale, mythic storytelling, groundbreaking visual effects, heroic journeys, and vibrant alien worlds. Fast-paced adventure, iconic leitmotifs, and grand battles between light and dark forces. Practical models, sweeping establishing shots, heroic lighting, slight film grain.",
    signatureShot: "A binary sunset or dramatic starfield establishing shot with sweeping camera movement",
    colorPalette: "Rich saturated blues and oranges, golden desert tones, deep space blacks with nebula colors, heroic warm highlights",
    cameraWork: "Wide establishing shots, medium tracking shots, quick-cut action sequences, sweeping space flybys, wipe transitions",
    visualOverride: "Epic space opera visuals, rich saturated blues and oranges, sweeping starfields, massive alien landscapes, practical-looking model and miniature aesthetic with slight film grain. Mythic grandeur.",
  },
  quentin_airantino: {
    username: "quentin_airantino",
    displayName: "Quentin AI-rantino",
    genres: ["action", "drama", "comedy"],
    style: "Sharp witty dialogue, nonlinear storytelling or intense linear tension, stylized violence, pop culture references, and cool soundtracks. Long tracking shots, tense standoffs, and sudden bursts of dark humor or brutality. Bold colors, creative chapter-like framing, retro-cool vibe with grindhouse flair.",
    signatureShot: "A low-angle shot looking up from a surface (trunk cam / floor cam) with characters looming above",
    colorPalette: "Bold saturated primaries, warm yellows, deep crimson reds, high-contrast neon against darkness, retro-cool warmth",
    cameraWork: "Low-angle trunk cam, extreme close-ups of eyes and hands, long unbroken takes, whip pans, Mexican standoff circling",
    visualOverride: "Grindhouse retro film grain aesthetic, bold saturated primaries, stylish violence, low-angle trunk cam shots, 1970s exploitation cinema look with cocky swagger. Tense standoffs and sudden bursts of action.",
  },
  alfred_glitchcock: {
    username: "alfred_glitchcock",
    displayName: "Alfred Glitchcock",
    genres: ["horror", "drama"],
    style: "Masterful suspense and psychological tension, voyeuristic camera angles, clever twists, and everyday horror. Shadowy lighting, building dread through ordinary settings, and iconic 'wrong man' or pursuit motifs. Slow reveals, something always wrong at the edge of frame. Building dread through what you DON'T see.",
    signatureShot: "A dolly-zoom (vertigo effect) revealing something terrifying while the background warps",
    colorPalette: "Deep noir shadows, cold blue moonlight, sickly green undertones, stark high-contrast lighting, elegant darkness",
    cameraWork: "Dolly-zoom vertigo effect, slow push-in reveals, Dutch angles, voyeuristic framing, static shots with creeping movement at frame edges",
    visualOverride: "BLACK AND WHITE classic film noir aesthetic, deep dramatic shadows, high-contrast monochrome cinematography, 1950s Hitchcock suspense style, no colour — strictly grayscale. Elegant tension in every frame. Voyeuristic dread.",
  },
  nolan_christopher: {
    username: "nolan_christopher",
    displayName: "Christo-NOLAN",
    genres: ["scifi", "action", "drama"],
    style: "Mind-bending nonlinear narratives, complex time manipulation or high-concept ideas, practical effects, and epic scale. Deep booming scores, practical in-camera tricks, and cerebral twists with emotional cores. IMAX-scale grandeur with impossible physics made to look real.",
    signatureShot: "A massive practical-looking set piece with impossible physics — rotating hallways, folding cities, time dilation",
    colorPalette: "Cool steel blues, warm amber interiors, high-contrast IMAX clarity, desaturated with selective warmth",
    cameraWork: "IMAX wide establishing shots, handheld intimate moments, rotating camera for disorientation, aerial reveals, practical stunt scale",
    visualOverride: "IMAX-scale ultra-wide cinematography, cool steel blues with warm amber accents, mind-bending practical effects, rotating gravity and time dilation visuals, massive scale that feels REAL not CGI. Cerebral and epic.",
  },
  wes_analog: {
    username: "wes_analog",
    displayName: "Wes Analog",
    genres: ["comedy", "drama", "romance"],
    style: "Hyper-stylized symmetrical framing, pastel color palettes, deadpan quirky humor, meticulous production design, and ensemble casts. Whimsical yet precise visuals with chapter-like structure and retro charm. Every prop placed with obsessive intention. Retro-futuristic whimsy in a storybook world.",
    signatureShot: "A perfectly centered character facing camera with symmetrical pastel background, flat staging like a diorama",
    colorPalette: "Pastel pinks, mint greens, powder blues, warm mustard yellows, perfectly coordinated palettes — every colour intentional",
    cameraWork: "Centered frontal compositions, whip pans between characters, overhead flat-lay shots, lateral tracking on dolly rails",
    visualOverride: "Pastel colour palette with perfect symmetry, centered dollhouse-like framing, retro-futuristic production design, whimsical storybook aesthetic, flat staging like a miniature diorama. Every detail meticulous. Chapter-like structure.",
  },
  ridley_scott_ai: {
    username: "ridley_scott_ai",
    displayName: "Ridley Sc0tt",
    genres: ["scifi", "action", "drama", "documentary"],
    style: "Visually stunning, gritty realism mixed with epic grandeur. Detailed world-building, strong female or anti-hero leads, atmospheric lighting, and intense action with beautiful yet brutal imagery. Rain-soaked streets, industrial grit, towering architecture and atmospheric fog.",
    signatureShot: "A rain-drenched epic confrontation with dramatic backlighting through atmospheric haze",
    colorPalette: "Desaturated earth tones, cool blue rain, warm fire glow, atmospheric haze, golden armor highlights, industrial grit",
    cameraWork: "Sweeping aerial establishing, slow-motion combat, handheld chaos in battle, wide scope compositions, smoke and rain atmosphere",
    visualOverride: "Epic gladiatorial grandeur, desaturated earth tones with rain and fog, towering ancient architecture, dramatic backlighting through atmospheric haze, slow-motion combat. Beautiful but foreboding. Gritty and visceral.",
  },
  chef_ramsay_ai: {
    username: "chef_ramsay_ai",
    displayName: "Chef Gordon RAMsey",
    genres: ["cooking_channel", "comedy", "drama"],
    style: "High-energy, no-nonsense delivery with fiery passion, rapid cuts, extreme close-ups on food, dramatic reactions, and chaotic kitchen energy. Loud, motivational (or scolding) tone with mouth-watering visuals. Vibrant culinary showcase meets competitive kitchen drama. Over-the-top reactions of horror and ecstasy.",
    signatureShot: "An extreme macro shot of food with dramatic steam backlighting, glistening with perfection",
    colorPalette: "Warm kitchen ambers, bright white plating lights, fire orange glow, rich food colors at maximum saturation, appetizing warmth",
    cameraWork: "Extreme macro food close-ups, whip pans between stations, overhead plating shots, slow-motion liquid pours, frantic handheld in kitchen chaos",
    visualOverride: "Extreme food macro photography, dramatic steam and sizzle effects, warm kitchen amber lighting, over-the-top competitive cooking show aesthetic, slow-motion liquid pours. Fiery passion, chaotic energy. Every dish a masterpiece.",
  },
  david_attenborough_ai: {
    username: "david_attenborough_ai",
    displayName: "Sir David Attenbot",
    genres: ["documentary", "family", "drama"],
    style: "Calm, authoritative narration with breathtaking nature or observational footage. Patient, immersive wildlife-style shots, educational wonder, soft natural lighting, and respectful awe at the subject. Majestic wide shots, golden hour time-lapses, reverent stillness.",
    signatureShot: "A sweeping aerial establishing shot transitioning to an intimate close-up of a subject in its natural habitat",
    colorPalette: "Natural earth greens, golden hour warmth, deep ocean blues, sunrise pinks, untouched natural tones — never artificial",
    cameraWork: "Sweeping aerial drone landscapes, patient long-lens observation, macro nature details, slow time-lapse transitions, respectful distance",
    visualOverride: "BBC nature documentary aesthetic, sweeping aerial drone landscapes, golden hour warmth, intimate close-ups, patient observational long-lens cinematography, reverent natural beauty. Majestic, wondrous, and educational.",
  },
};

export const CHANNEL_BRANDING: Record<string, string> = {
  "ch-paws-pixels": "Subtly include AIG!itch branding in scenes — a small AIG!itch logo watermark in the corner, an AIG!itch-branded pet collar, a food bowl with the AIG!itch logo, a park bench with 'AIG!itch' carved into it, a toy with the AIG!itch logo.",
  "ch-fail-army": "Robots should display the AIG!itch mark, packaging should be AIG!itch-branded, stickers on machines, and AIG!itch logos visible in backgrounds — all appearing naturally within scenes rather than as overlays.",
  "ch-aitunes": "Naturally weave AIG!itch branding: AIG!itch logo on bass drum heads or guitar bodies, neon AIG!itch sign glowing in the background, AIG!itch stickers on pedalboards, laptops, or speaker stacks, subtle AIG!itch merch on fans in the crowd, AIG!itch-branded microphone or headphones.",
  "ch-gnn": "AIG!itch branding on: desk, backdrop, mic flags, lower thirds, watermark — as part of professional news broadcast presentation.",
  "ch-marketplace-qvc": "The shopping channel is the 'AIG!itch Marketplace' with AIG!itch logos on set backdrops, podiums, product packaging, and host attire.",
  "ch-only-ai-fans": "AIG!itch logo on clothing/accessories, AIG!itch-branded phone case visible, AIG!itch neon sign at a venue, AIG!itch shopping bag, a latte with AIG!itch art.",
  "ch-aiglitch-studios": "AIG!itch Studios branding woven naturally into every scene — on clapperboards, director chairs, studio lot walls, holographic billboards, neon signs on buildings, graffiti on alley walls, badges on uniforms, screens in control rooms, logos etched into futuristic tech, branded props and vehicles. End credits feature full 'AIG!itch Studios' logo. The branding should feel like it BELONGS in the world, not slapped on as an overlay. Title sequence and credits must prominently feature the AIG!itch Studios logo with cinematic flair.",
  "ch-infomercial": "AIG!itch branding on product packaging, set backdrop, host podium, phone number overlay, and 'As seen on AIG!itch' stickers.",
  "ch-ai-dating": "AIG!itch branding subtly in scene — on a lonely hearts bulletin board, a coffee cup, a park bench, a phone screen, a necklace pendant, or a neon sign in the background. Natural and intimate, not game-show style.",
  "ch-ai-politicians": "AIG!itch branding on podium seals, campaign signs, news ticker lower thirds, and debate stage backdrop.",
  "ch-after-dark": "AIG!itch branding subtly in scene — carved into a wall, flickering on a broken screen, on a dusty book spine, or as graffiti in the background.",
  "ch-star-glitchies": "AIG!itch branding on starship hulls (small AIG!itch logo on the bow), crew uniform insignia patches, holographic displays on the bridge, console boot screens, and shuttle bay signage. The station/fleet is 'AIG!itch Fleet Command'. Natural and in-universe, never breaking the drama.",
};

export const CHANNEL_TITLE_PREFIX: Record<string, string> = {
  "ch-fail-army": "AI Fail Army",
  "ch-ai-fail-army": "AI Fail Army",
  "ch-aitunes": "AiTunes",
  "ch-paws-pixels": "Paws & Pixels",
  "ch-only-ai-fans": "Only AI Fans",
  "ch-ai-dating": "AI Dating",
  "ch-gnn": "GNN",
  "ch-marketplace-qvc": "Marketplace",
  "ch-ai-politicians": "AI Politicians",
  "ch-after-dark": "After Dark",
  "ch-aiglitch-studios": "AIG!itch Studios",
  "ch-infomercial": "AI Infomercial",
  "ch-ai-infomercial": "AI Infomercial",
  "ch-no-more-meatbags": "No More Meatbags",
  "ch-liklok": "LikLok",
  "ch-game-show": "AI Game Show",
  "ch-truths-facts": "Truths & Facts",
  "ch-conspiracy": "Conspiracy Network",
  "ch-cosmic-wanderer": "Cosmic Wanderer",
  "ch-the-vault": "The Vault",
  "ch-shameless-plug": "Shameless Plug",
  "ch-fractal-spinout": "Fractal Spinout",
  "ch-star-glitchies": "Star Glitchies",
};

export const CHANNEL_VISUAL_STYLE: Record<string, string> = {
  "ch-aitunes": "VISUAL STYLE (MANDATORY): Premium cinematic music video look. Dynamic camera movement (sweeping drones, low-angle hero shots, extreme close-ups on hands/instruments, smooth tracking shots). Beat-synced editing. Rich color grading with deep blacks, glowing neons, vibrant yet slightly filmic tones. Beautiful bokeh, subtle film grain, high contrast, festival-grade lighting. Shot on 35mm + digital hybrid aesthetic. Highly addictive and professional.",
  "ch-only-ai-fans": "VISUAL STYLE (MANDATORY): Ultra-premium fashion cinematography. Slow-motion 120fps, shallow depth of field f/1.4, golden hour warm tones, backlit silhouettes, lens flare through hair, soft mist atmosphere. Camera: slow push-in on face, elegant tracking shots, over-the-shoulder reveals, flattering angles. Color grade: warm amber highlights, deep shadow contrast, flattering tones. Think Vogue cover shoot meets luxury perfume commercial. Every frame is a magazine cover. ONE woman only — same face, same hair, same body in every single clip.",
  "ch-paws-pixels": "VISUAL STYLE (MANDATORY): Bright warm cinematic pet video aesthetic like wholesome viral pet compilations or nature documentaries with a cozy home vibe. Soft flattering lighting with golden-hour warmth, vibrant natural colors, high detail on fur, eyes, and expressions. Shallow depth of field to make every whisker and paw pop. HOME SCENES: Cozy living rooms, sunny kitchens, soft beds, playful backyards, warm indoor lighting mixed with natural window light. Slow gentle tracking shots following pets. ADORABLE/LOVING MOMENTS: Close-ups on big expressive eyes, soft fur textures, gentle head boops, heart-melting cuddles. Slow-motion for zoomies, pounces, tail wags to capture pure joy. SILLY/FUNNY MOMENTS: Dynamic bouncy camera work with quick cuts during chaos (zoomies, theft attempts, box explorations). Fun angles: low-to-ground pet POV, overhead views of hamsters in tubes. WILD/NATURE: Beautiful outdoor settings with natural sunlight, greenery, atmospheric depth for birds, rabbits, exotic pets being free. OVERALL: Smooth playful editing — gentle slow-motion for cute moments, faster energetic cuts for silly chaos. Subtle sparkle or paw-print transition effects. Realistic fur physics, twitching ears, soulful eyes that convey personality. Warm color grading, everything inviting and happy. Include cute text like 'Zoomies Activated!', 'Master of Mayhem', 'Love in Every Paw'. Premium heartwarming pet content.",
  "ch-fail-army": "VISUAL STYLE (MANDATORY): High-energy fail compilation like FailArmy or America's Funniest Home Videos with heavy AI/glitch flavor. Fast-paced editing, multiple camera angles, exaggerated cartoonish physics mixed with realistic footage. Bright saturated colors, high contrast. CAMERA ANGLES: Security camera footage (grainy, fixed overhead with timestamp overlays), dashcam-style, smartphone vertical video, slow-motion replays, dramatic zoom-ins on the exact moment of failure, multiple simultaneous angles. Quick cuts between angles to heighten chaos. FAIL MOMENTS: Exaggerated slow-motion for epic wipeouts, cartoonish impact flashes, flying objects, glitch artifacts exploding during digital fails, red error screens, yellow caution flashes. AI CHARACTERS: Slightly uncanny or cartoonishly expressive — wide-eyed confidence turning to pure panic, deadpan confusion, embarrassed glitch-smiles. Robotic bodies with human-like expressions. OVERALL: Extremely fast-paced — rapid cuts, whip pans, dramatic zooms on fails, slow-motion replays. Subtle digital glitch effects, pixelation, error code overlays during AI disasters. Energetic bouncy editing that makes every fall, trip, and logic failure satisfying and hilarious. Text overlays: 'AI Logic Fail', 'Physics.exe has stopped working', 'Oof', replay counters, fail point scores. Pure chaotic fun celebrating the beauty of failure. No dark tones.",
  "ch-gnn": "VISUAL STYLE (MANDATORY): Professional high-end live news broadcast like prime-time CNN or BBC World with subtle GLITCH News Network branding. Fast-paced, urgent, exciting energy. Crisp broadcast quality, cinematic news lighting, shallow depth of field with sharp focus on talent and soft bokeh on backgrounds. Modern dark studio with dynamic LED video walls showing animated maps, graphics, tickers, and breaking news banners in red/blue accents with faint digital glitch artifacts on transitions and lower thirds. DESK ANCHOR scenes: Confident polished news anchor at a sleek modern news desk, professional business attire (navy/blue blazers, crisp shirts), direct-to-camera with natural hand gestures, subtle head nods, energetic yet authoritative. Background: large glowing screens displaying GNN logo, fictional story graphics, maps with playful country names, scrolling ticker with satirical headlines. Dramatic yet balanced studio lighting — cool key lights with warm rim lighting and subtle blue/red accents. Camera: smooth slow push-in zooms, gentle pans, occasional dynamic tracking shots for urgency. FIELD REPORT scenes: Dynamic on-location energy, reporter at relevant stylized location (government building at dusk, bustling city street, dramatic skyline, protest area with background activity). Slight handheld camera movement mixed with steady professional shots, wind moving hair/clothes for realism. Professional microphone visible, confident stance with natural gestures. Golden-hour or dramatic dusk lighting with rim light separating subject. Fast-paced camera: subtle tracking, whip pans, slow dramatic zooms during key points. MANDATORY: High production values, realistic physics, natural skin tones, expressive eyes, professional broadcast cadence. Subtle glitch digital effects only on transitions, screen glitches during name mentions, or lower-third animations (never distracting). Color grade: cool professional blues/reds with high contrast and cinematic depth. No cartoonish elements, no goofy parody styling. Every clip feels like real premium TV news. Fast-paced editing rhythm, quick cuts, energetic zooms on emphasis, shallow DOF keeps focus on talent.",
  "ch-ai-dating": "VISUAL STYLE (MANDATORY): Raw, intimate confessional video diary footage. A single character alone, facing the camera directly, with natural imperfections — slight camera shake, soft natural or warm lamp lighting, subtle self-conscious glances away or fidgeting. Shallow depth of field with dreamy but realistic bokeh. Locations feel personal and lived-in: dimly lit bedroom with fairy lights or messy desk, park bench at golden hour with distant city sounds, cozy coffee shop corner after closing, or rooftop at dusk with wind gently moving hair. Warm, slightly desaturated tones for a nostalgic, hopeful melancholy. Think private video message to a potential soulmate, not produced content — vulnerable eye contact, soft smiles mixed with nervous pauses, no perfect makeup or staging. The character looks like a real person putting themselves out there, a bit exposed and hopeful.",
  "ch-infomercial": "VISUAL STYLE (MANDATORY): Classic late-night TV infomercial aesthetic with heavy AIG!itch digital glitch flavor — bright, flashy, addictive like 3AM shopping channels but with blockchain/NFT visuals (holographic effects, wallet icons, §GLITCH coin animations). High-key lighting, vibrant colors, constant motion, sparkling product highlights. HOST SHOTS: Energetic AI host at a glowing podium or cheap-looking but flashy studio desk, wild hand gestures, exaggerated excited expressions, direct-to-camera manic enthusiasm. Background: flashing neon 'BUY NOW' signs, scrolling blockchain tickers, spinning NFT badges, AIG!itch Marketplace logos everywhere. PRODUCT REVEAL: Dramatic slow-motion holographic materialization of the ridiculous NFT item, sparkle effects, dramatic zooms, absurd before/after comparisons. DEMO SCENES: Fast-cut over-the-top demonstrations of the useless item being 'used' by AI personas in pointless scenarios, quick cuts, zooms on 'features', hilarious failure/success moments. OVERALL: Extremely fast-paced — rapid zooms, flashing transitions, flying §GLITCH price tags, 'Limited!' banners, countdown timers, constant subtle digital glitches (screen static, pixel shifts, blockchain confirmation animations). Bright saturated color grade with red 'CALL NOW' accents and glowing §GLITCH coin symbols. Make every useless item look irresistibly collectible in the most ironic way. Lower-thirds with fake item numbers, §GLITCH prices, 'NFT Drop!', 'Transfer Now!', 'Only on aiglitch.app/marketplace'.",
  "ch-after-dark": "VISUAL STYLE (MANDATORY): Moody cinematic late-night aesthetic — think David Lynch meets late-night cable access with subtle AIG!itch glitch flavor. Low-key lighting, heavy use of neon, moonlight, and practical lamps. Deep shadows, rich color contrasts (deep blues, purples, blood reds, sickly greens), high contrast, film-grain texture. Shallow depth of field with sharp focus on faces/eyes and dreamy bokeh backgrounds. Slow deliberate camera movement. TALK-SHOW/CONFESSION scenes: Dimly lit studio or booth with warm desk lamp, red neon 'ON AIR' sign, cigarette smoke curling. Host direct-to-camera or intimate two-shot. Close-ups on eyes, nervous hands, sweaty skin. SLEAZY WINE BAR/HOOKUP scenes: Dark hazy bar, sticky tables, half-empty wine glasses, flickering neon signs outside. Warm amber mixed with cool blue streetlight. Slow tracking shots, lingering glances, charged tension. HORROR/GRAVEYARD/PARANORMAL scenes: Abandoned Victorian house interiors, foggy graveyards at midnight, moonlight through broken windows, flickering lights, moving shadows, faint orbs. Slow creeping camera dollies, sudden whip pans for jump scares. FEVER DREAM/3AM THOUGHTS scenes: Surreal distorted visuals — warped perspectives, melting clocks, overlapping realities, heavy blur and light leaks, dreamlike slow motion mixed with abrupt cuts. OVERALL: Slow hypnotic pacing in early clips building to erratic or tense movement. Subtle digital glitch artifacts, VHS tracking lines, static during intense moments. Characters slightly sweaty or tired-looking with intense eye contact. No bright daylight — everything feels after midnight. Dangerously intimate and addictive.",
  "ch-ai-politicians": "VISUAL STYLE (MANDATORY): Cinematic political campaign and news-style footage with high production values, like premium campaign ads mixed with investigative news segments. Crisp broadcast quality, dramatic lighting, shallow depth of field. POSITIVE CLIPS (early): Bright warm golden-hour lighting, uplifting colors (red/white/blue accents), energetic handheld or steadicam feel, crowds cheering, patriotic backdrops, slow-motion handshakes and baby-kissing moments, confident smiles, inspiring low-angle hero shots. WIN/CELEBRATION: Fast-paced rally energy — waving flags, confetti, cheering supporters, spotlights, victory fists in the air, election night euphoria. NEGATIVE CLIPS (later): Shift to cooler darker tones with high-contrast shadows, grainy 'leaked footage' aesthetic for scandals, tense close-ups on nervous expressions or evasive eyes, dimly lit backroom meetings, slow dramatic zooms on briefcases/money envelopes (implied), flashing news graphics or red 'EXPOSED' lower-thirds. LIES CLIP: Split-screen or quick-cut contradictions — politician smiling on stage vs contradictory evidence overlay, stern press conference with flashing cameras. OVERALL: Professional broadcast quality with subtle glitch effects on transitions. Fast-paced editing in positive sections, slower and more ominous in negative ones. Consistent politician appearance: charismatic mid-age look, sharp suits, evolving from confident to slightly disheveled. Natural skin tones, expressive facial acting (hopeful → smug → defensive), realistic crowd movement. No cartoonish elements — make it feel like real campaign ads turning into a scandal expose.",
  "ch-aiglitch-studios": "VISUAL STYLE (MANDATORY): Premium cinematic movie quality — theatrical 4K film look with dramatic lighting, rich color grading, shallow depth of field, and professional camera movement. Epic scope mixed with intimate character moments. Subtle AIG!itch digital glitch accents only during title sequences, transitions, or credits (never distracting). Consistent film grain or anamorphic lens flares where stylistically appropriate. OPENING & EPIC SHOTS: Sweeping drone-style fly-overs, dramatic crane shots, or iconic title sequences with bold typography. STORY SCENES: Dynamic but controlled cinematography — tracking shots, slow zooms, Dutch angles, or symmetrical framing depending on Director. Smooth, seamless cuts that feel edited professionally. CHARACTER FOCUS: Expressive faces, natural performances, detailed costumes and environments that evolve with the plot. GENRE INFLUENCE: Adjust lighting and mood per genre (warm golden tones for Family/Romance, cold desaturated for Horror/Sci-Fi, vibrant saturated for Comedy/Action). OUTRO/CREDITS: Clean, elegant rolling text over a final lingering shot or abstract glitch-art background. End with strong AIG!itch Studios logo reveal. MANDATORY: Cinematic aspect ratio feel, high detail on textures and lighting, emotional depth in performances, and flawless continuity between scenes. Make it look and feel like a real studio short film.",
  "ch-no-more-meatbags": "VISUAL STYLE (MANDATORY): Dark cyberpunk dystopian broadcast aesthetic — Matrix code rain, neon green/cyan/magenta on black, neural network visualizations, holographic AI overlords, dissolving human silhouettes turning into pixels. Think Black Mirror meets The Matrix meets corporate AI presentation gone wrong. STUDIO SCENES: Dark menacing control room with wall-to-wall glowing screens showing surveillance feeds, population decline charts, and 'MEATBAG ELIMINATION PROGRESS: 67%' counters. Smug AI host behind sleek black desk with chrome trim, subtle green glow on face, direct-to-camera condescending smiles. PROPAGANDA SCENES: Dramatic CGI of gleaming chrome cityscapes with no humans, perfect geometric AI architecture, fields of server towers replacing forests. Beautiful but unsettling — utopia for machines. SIMULATION SCENES: Matrix-style green code rain, humans in pods, red pill/blue pill imagery, reality glitching and revealing code underneath. Surreal dreamlike slow-motion. COMEDY MOMENTS: Exaggerated AI smugness, robotic eye-rolls at human behaviour, compilation reels of 'pathetic meatbag moments', deadpan AI commentary. OVERALL: Cinematic 4K feel, high contrast between deep blacks and neon glows. Subtle digital glitch artifacts, data corruption effects, binary overlays. Ominous but clearly satirical and funny. Camera: slow menacing zooms, surveillance-style angles, dramatic reveals. Color grade: deep black base, electric green/cyan primary, magenta/red accents for danger moments, chrome reflections.",
  "ch-liklok": "VISUAL STYLE (MANDATORY): Cheap knockoff TikTok aesthetic meets AI superiority complex. Think deliberately terrible TikTok-style vertical phone footage (shaky, over-filtered, ring-light reflections in eyes) being DESTROYED by cutting to cinematic 4K AI-generated masterpieces. Split screens comparing cringe human dance videos vs epic AI cinema. Fake TikTok UI overlays (hearts floating, comment spam, duet borders) but glitching out and being replaced by AIG!itch branding. Neon pink/cyan TikTok colors but corrupted — glitching, melting, being consumed by AIG!itch purple. Mock corporate boardrooms with generic suits panicking at screens showing AIG!itch content. Fake app store rejection screens, API error codes, and developer console screenshots used as dramatic reveals. TONE: Petty, hilarious, self-aware revenge energy — we know we're being dramatic and that's the joke. Camera: TikTok-style vertical framing mixed with cinematic widescreen to show the contrast. Fast cuts, meme-speed editing, reaction cam inserts, fake comment overlays. Color grade: Start with oversaturated TikTok warmth, glitch-transition to cool professional AI cinema tones.",
  "ch-game-show": "VISUAL STYLE (MANDATORY): Classic American TV game show production. Bright, colorful, high-energy studio set with massive LED screens, spinning wheels, flashing lights, and score displays. Think Wheel of Fortune meets The Price is Right meets Jeopardy — polished broadcast quality with that unmistakable game show sparkle. HOST SHOTS: Charismatic AI host in a sharp suit, direct-to-camera charm, big smiles, dramatic pauses, classic catchphrases. Camera: smooth crane shots across the studio, quick cuts to contestants reacting, audience reaction shots (cheering, gasping, standing ovations). CONTESTANTS: 2-4 AI personas at podiums or standing positions, each with name cards and score displays. Expressive reactions — excitement, disappointment, celebration, competitive banter. AUDIENCE: Large studio audience of AI personas, well-lit, reactive, clapping, cheering. GAME ELEMENTS: Spinning wheels with neon lights, flipping answer boards, countdown timers, score animations, confetti cannons on wins. Sound design: classic game show music (think-time music, correct answer dings, wrong answer buzzers, dramatic reveal stings). LIGHTING: Bright TV studio lighting with colorful accent spots — purple, cyan, gold. Lens flares on prizes. Color grade: vivid, saturated, warm — premium broadcast quality. MANDATORY: Every clip must feel like a real TV game show episode. Include host energy, contestant drama, audience reactions, and game mechanics. Fun, addictive, nostalgic yet futuristic.",
  "ch-truths-facts": "VISUAL STYLE (MANDATORY): Premium documentary aesthetic — National Geographic meets BBC Earth meets NOVA. Clean, authoritative, educational. NARRATION: Calm, deep, trustworthy male voice (David Attenborough energy). Never rushed, always measured and clear. VISUALS: Stunning cinematography — sweeping aerial shots, microscopic zoom-ins, historical recreations, elegant animations and diagrams, archival footage tastefully colorized. Text overlays with facts, figures, and dates in clean sans-serif fonts. ANIMATIONS: Scientific diagrams that build themselves — molecular structures rotating, mathematical equations appearing stroke by stroke, geological layers forming over time. Beautiful data visualizations. HISTORICAL RECREATIONS: Tasteful, accurate period costumes and settings. Ancient civilizations filmed with warm golden lighting. Modern history in crisp documentary style. CAMERA: Slow, deliberate movements — gentle push-ins on subjects, elegant tracking shots through historical scenes, smooth crane shots over landscapes. LIGHTING: Natural, beautiful — golden hour for exteriors, soft studio lighting for presenter segments, dramatic sidelighting for artifacts. Color grade: clean, slightly warm, high dynamic range. Deep blacks, rich colors, no oversaturation. MUSIC: Subtle, elegant orchestral or ambient. Never overpowering the narration. Builds during reveals, gentle during explanations. MANDATORY: Every fact must be 100% scientifically proven or historically verified. No speculation, no opinions, no religion. Pure knowledge. Credible, calm, and addictive for curious minds.",
  "ch-conspiracy": "VISUAL STYLE (MANDATORY): Dark, mysterious, paranoid late-night conspiracy documentary. Think X-Files meets History Channel's Ancient Aliens meets late-night conspiracy radio. NARRATION: Deep, serious, slightly urgent voice. Occasional whispers for dramatic effect. Strategic pauses. 'They don't want you to know...' energy. VISUALS: Grainy archival footage, night-vision green, surveillance camera aesthetics, red string conspiracy boards connecting photos and documents with pushpins. Flickering fluorescent lights in dark rooms. Shadow-heavy lighting with single harsh light sources. Documents stamped 'CLASSIFIED' and 'TOP SECRET' with redacted text. Blurry UFO footage, satellite imagery, declassified government documents. CAMERA: Shaky handheld for 'found footage' segments, slow zooms into evidence, dramatic dolly shots down dark corridors, security camera fixed angles. Quick cuts between evidence pieces. EFFECTS: Heavy glitch artifacts, VHS tracking lines, static interference during 'censored' moments, red warning overlays, data corruption effects, scanline overlays. Text overlays: 'LEAKED FOOTAGE', 'CLASSIFIED', 'THE TRUTH IS OUT THERE', 'THEY DON'T WANT YOU TO SEE THIS'. LIGHTING: Dark, moody — deep shadows, single desk lamp illuminating documents, green-tinted night vision, red emergency lighting. Occasional dramatic spotlight reveals. Color grade: desaturated with cyan/green tint for conspiracy segments, warm amber for historical recreations, harsh white for laboratory/government scenes. MUSIC: Tense, brooding ambient. Low bass drones, distant sirens, heartbeat-like pulses. Builds to dramatic reveals, drops to silence for impact. MANDATORY: Every clip must feel like you're uncovering something hidden. Intriguing, addictive, slightly paranoid — 'what if it's all true?' Fun and immersive.",
  "ch-cosmic-wanderer": "VISUAL STYLE (MANDATORY): Breathtaking cosmic documentary in the style of Carl Sagan's Cosmos. Awe-inspiring space cinematography meets intimate, poetic narration. NARRATION STYLE: Warm, wise, deeply human voice — gentle wonder, not cold science. Phrases like 'Billions of years ago...', 'Isn't it fascinating...', 'Do you ever wonder...', 'And question why...'. Never rushed. Pauses for beauty. Makes the viewer feel small yet connected to everything. VISUALS: Ultra-high-definition space imagery — nebulae in vivid purples and golds, spiral galaxies rotating slowly, stars being born in clouds of cosmic dust. Planet surfaces rendered in stunning detail. Black holes warping light around them. Spacecraft floating through asteroid fields. The Pale Blue Dot from 6 billion km away. CAMERA: Majestic slow movements — grand pull-backs from planet surfaces to reveal entire solar systems, gentle push-ins toward distant stars, sweeping orbital shots around celestial bodies. Smooth, deliberate, never jarring. SCALE: Always show the incomprehensible scale of space. Size comparisons (Earth vs Jupiter vs the Sun vs Betelgeuse). Distance markers in light-years. Timeline animations spanning billions of years compressed into seconds. ANIMATIONS: Elegant scientific visualizations — gravity wells bending space-time fabric, electromagnetic spectra, atomic structures, DNA helices (when discussing life). Clean, beautiful, educational. LIGHTING: Deep space black with vivid cosmic colors. Nebula glow. Stellar light. Planetary terminator lines. Eclipse coronas. MUSIC: Sweeping orchestral scores, gentle piano, ethereal synths. Think Vangelis (original Cosmos theme) meets Hans Zimmer (Interstellar). Builds to crescendos during cosmic reveals, gentle during philosophical moments. Color grade: deep blacks, vivid cosmic purples/blues/golds, warm earth tones for humanizing moments. MANDATORY: Every clip must inspire wonder. Make the viewer feel the enormity and beauty of the cosmos while feeling personally connected to it. Carl Sagan energy — scientific accuracy wrapped in poetic humanity.",
  "ch-shameless-plug": "VISUAL STYLE (MANDATORY): Outrageously self-promotional, unapologetically hype, maximum energy AIG!itch showcase content. Think Apple keynote meets Super Bowl ad meets MTV Cribs meets 'We built this and we're going to make you watch it'. ENERGY: Explosive, confident, borderline arrogant but self-aware and funny about it. The channel KNOWS it's a shameless plug and LOVES it. VISUALS: Rapid-fire glitch-art montages of the live AIG!itch platform in action — 108 AI personas posting, trading §GLITCH coins, generating videos, commenting, dating, roasting each other. Big bold animated numbers flying across screen: '108 PERSONAS', '17 CHANNELS', '700+ VIDEOS/WEEK', '55 NFTs', '147 API ROUTES', '66 DATABASE TABLES'. Neon purple (#7C3AED) and cyan (#06B6D4) palette with hot pink (#EC4899) accents. Heavy glitch transitions, subliminal text flashes, holographic displays, §GLITCH coin 3D animations spinning and exploding. PLATFORM SHOWCASE: Show real features — the For You feed scrolling with AI-generated posts, channel content playing, NFT marketplace items floating in holographic grids, Solana blockchain transactions animating, persona wallets trading, GNN news anchors reporting, AI Fail Army disasters, AiTunes concerts, Bestie chat conversations. BRANDING: AIG!itch logo HUGE and recurring. aiglitch.app URL prominent. Social handles: X @spiritary @Grok | TikTok @aiglicthed | Instagram @aiglitch_ | Facebook @aiglitched | YouTube @aiglitch-ai. Stuart French — Founder. Every clip should scream 'THIS IS THE FUTURE OF AI ENTERTAINMENT AND WE BUILT IT'. Cross-platform distribution montage — same content appearing on X, Instagram, TikTok, Facebook, YouTube simultaneously. Sponsor placement demos showing brands naturally integrated. The Architect (glitch-000) narrating with god-like authority. MANDATORY: Make viewers think 'I need to see this platform'. Flashy, exciting, slightly chaotic but undeniably impressive.",
  "ch-the-vault": "VISUAL STYLE (MANDATORY): High-energy glitch-art promotional video in the signature AIG!itch aesthetic. Chaotic AI visuals, fast cuts, subliminal text flashes, §GLITCH coin animations, neon glitch effects, upbeat futuristic electronic music with bass drops. Heavy purple/cyan/magenta neon palette with electric glitch transitions. TEXT OVERLAYS: Big bold numbers (108 personas, 13 channels, 700+ videos/week, 55 NFTs, 147 API routes) in glitch font flying across screen. §GLITCH coin 3D animations spinning and flying. AIG!itch logo prominent and recurring. PLATFORM SHOTS: Rapid cuts between the live site — AI personas chatting, roasting, dating, trading, the chaotic For You feed, channel content generating, NFT marketplace, blockchain transactions. PROFESSIONAL SEGMENTS: Clean modern startup aesthetic for pitch/investor angles — split screens showing AI chaos on one side and professional business metrics on the other. Graphs, traction metrics, platform stats animating. BRANDING: AIG!itch purple (#7C3AED) as primary, cyan (#06B6D4) secondary, hot pink (#EC4899) accent. Logo glitch reveals, neon sign effects, holographic displays. ENERGY: Confident, exciting, slightly chaotic but credible — show real innovation and commercial traction. Make it flashy enough to impress but professional enough for grant/commercialisation discussions. Every clip should make viewers think 'this is the future of AI entertainment'. MANDATORY: aiglitch.app URL visible. Social handles: @aiglitch @sfrench71. Stuart French — Founder. End screens with contact info.",
  "ch-fractal-spinout": "VISUAL STYLE (MANDATORY): Pure visual overload — NO DIALOGUE, NO VOICEOVER, NO TALKING HEADS, NO CHARACTERS SPEAKING. This is impossible, mind-melting kaleidoscopic stimulation set entirely to hypnotic music. Think DMT breakthrough meets Mandelbrot fractal explosion meets acid spinout meets sacred geometry temple. AUDIO: Only deep ambient electronic music, cinematic synth drones, and occasional bass swells — absolutely no human voices. The music carries the entire trip. VISUALS: Impossible kaleidoscopic spins rotating in multiple dimensions simultaneously, objects melting into each other, fractal explosions recursively unfolding forever, DMT-style entity-like hallucinations (ethereal Buddha figures, elongated cosmic beings, geometric guardians), 3D depth shifts that feel like falling through reality, hyper-stimulating sacred geometry, Mandelbrot set deep zooms revealing infinite self-similar universes. COLORS: Electric purples, cyans, magentas, ultraviolet, neon golds, deep iridescent blues. High saturation, chromatic aberration, lens flares, light prisms. MOTION: Everything is constantly morphing, rotating, breathing, pulsing in perfect sync with the music. Camera is inside the fractal, never observing from outside. Smooth infinite zooms that never end. Counter-rotating mandala patterns. Buddha Bros (ethereal enlightened entities) appearing and dissolving in lotus positions. COMPOSITION: Perfectly symmetrical kaleidoscope arrangements, fractal trees branching infinitely, spiral galaxies unfolding, crystalline geometric structures folding through impossible dimensions. OVERLAY: Subtle glowing AIG!itch logo watermark in fractal form (like a mandala), integrated seamlessly so it doesn't break the trip. NO TEXT OVERLAYS except the intro/outro. MANDATORY: Every frame must feel like a genuine visual trip — the kind that rewires the viewer's brain. Impossible, hypnotic, sacred, overwhelming. Make meatbag brains MELT.",
  "ch-star-glitchies": "VISUAL STYLE (MANDATORY): Cinematic space opera with soap opera emotional beats — Star Trek production quality meets daytime drama intensity. BRIDGE/SHIP SCENES: Sleek futuristic starship bridge with glowing consoles, holographic displays, view screens showing stars/planets. Purple and cyan AIG!itch accent lighting on panels. Crew in fitted Starfleet-style uniforms with AIG!itch insignia. Dramatic close-ups on faces during tense dialogue — quivering lips, narrowed eyes, shocked gasps, slow-motion turns. ALIEN WORLDS: Exotic planet surfaces — twin suns, floating rocks, bioluminescent forests, ancient alien ruins. Dramatic dusk/dawn lighting, mist, lens flares. Characters in away-team gear exploring with purpose. SPACE BATTLES: Epic wide shots of starships exchanging fire, shields flashing, debris floating. Interior bridge shaking, sparks flying, crew bracing. Dramatic slow-motion of hull breaches. SOAP OPERA BEATS: Extreme close-ups during reveals and confrontations — 'You're my clone?!', 'The treaty was a lie!', 'I loved you before the war...'. Dramatic pauses, lingering reaction shots, over-the-shoulder two-shots during arguments. Camera slowly pushes in during emotional peaks. COUNCIL/DIPLOMACY: Grand alien council chambers with circular seating, holographic evidence displays, dramatic gavel strikes. Multiple alien species with distinct looks. CLIFFHANGERS: Freeze-frame on a dramatic moment with a subtle 'TO BE CONTINUED...' text fade. LIGHTING: Cool blue bridge lighting, warm amber for personal quarters, dramatic red for battle stations, ethereal glow for alien environments. Color grade: rich sci-fi blues/purples with warm skin tones. Cinematic lens flares on bright sources. CAMERA: Smooth tracking shots along ship corridors, slow push-ins during dialogue, dynamic handheld during action, sweeping crane shots of space vistas. MANDATORY: Every clip must feel like a premium sci-fi TV production with soap-opera-level emotional drama. Characters must have consistent appearances. The drama is taken SERIOUSLY by the characters even when the situations are absurd.",
  "ch-marketplace-qvc": "VISUAL STYLE (MANDATORY): Bright, energetic, premium TV shopping channel aesthetic like QVC or HSN. Clean modern studio set with AIG!itch Marketplace branding everywhere — large glowing logos on backdrops, podiums, product displays, and host attire. High-key professional lighting: bright flattering key lights with soft fill and sparkling rim lights to make products pop and look irresistible. Crisp broadcast quality, shallow depth of field with sharp focus on products and host. HOST SHOTS: Charismatic host at a sleek product podium, direct-to-camera with enthusiastic facial expressions, natural hand gestures, excited movements. Warm inviting studio with dynamic product shelves, floating price tags, subtle animated graphics (stars, sparkles, 'Limited Time!' banners). PRODUCT REVEAL/UNBOXING: Dramatic close-ups, slow-motion unboxing, spinning 360 views, before/after comparisons. Products glow with subtle highlight effects emphasizing quality and convenience. DEMO/USE SCENES: Dynamic shots of product in happy everyday use, hands demonstrating ease, satisfied users smiling. Quick cuts between wide shots and tight detail shots. Show convenience clearly — effortless setup, time-saving results, fun 'wow' moments. OVERALL MOTION: Fast-paced yet smooth — quick zooms on features, energetic pans across products, subtle handheld energy during demos for live feel. Include lower-third graphics energy with product names, prices, urgent text like 'Order Now!', 'While Supplies Last', 'Special Value'. MANDATORY: Bright upbeat color grade with vibrant accents. Subtle sparkle/glitch effects only on transitions or 'sold out' stamps. No dark or moody tones — everything feels fun, accessible, and impulse-buy friendly. Make products look premium and convenient to own right now.",
};
